version: '3'
volumes: 
  mysql:
networks:
  backend:


services:
  nginx:
      image: nginx:alpine
      ports:
        - "84:80"
      links:
        - php-fpm
      volumes:
        - ./testProject:/var/www/html
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - backend
  php-fpm:
      build: ./docker/php
      ports:
        - "9000:9000"
      env_file:
        - .env
      volumes:
        - ./testProject:/var/www/html
      networks:
        - backend
  mysql:
      image: mysql:5.7
      container_name: test_project_mysql
      restart: always
      volumes:
        - mysql:/var/lib/mysql
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      networks:
        - backend
  swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: "swagger-ui"
      ports:
        - "8082:8080"
      volumes:
        - ./testProject/swagger/openapi.yaml:/openapi.yaml
      environment:
        SWAGGER_JSON: /openapi.yaml